FROM alpine:3.18.0

WORKDIR /app

ARG APP_USER=www-data NODE_JS_VERSION=18.16.0-r1

RUN apk -U upgrade && apk add --no-cache nodejs=${NODE_JS_VERSION}

RUN delgroup ${APP_USER} 2>>/dev/null; addgroup -S -g 1001 ${APP_USER};

EXPOSE 9000

CMD [""]