version: '3'

services:
    mariadb:
      container_name: mariadb-container
      build:
        context: .
        dockerfile: Dockerfile-mariadb
      image: mariadb-try:v1
      volumes:
        - data:/var/lib/mysql
      env_file:
        - ../../.env
      networks:
        - wp-nginx-mariadb

networks:
  wp-nginx-mariadb:

volumes:
  data: