FROM alpine:3.18

WORKDIR /app

ARG APP_USER=mysql

RUN apk -U upgrade && \
    apk add --no-cache mysql mariadb mariadb-client procps vim

RUN mkdir -p /var/run/mysqld && \
    chown -R ${APP_USER}:${APP_USER} /var/run/mysqld && \
    chmod -R 750 /var/run/mysqld && \
    mkdir -p /var/lib/mysql && \
    chown -R ${APP_USER}:${APP_USER} /var/lib/mysql && \
    chmod -R 750 /var/lib/mysql && \
    mkdir -p /var/log/mysql && \
    chown -R ${APP_USER}:${APP_USER} /var/log/mysql && \
    chmod -R 750 /var/log/mysql

RUN mysql_install_db --user=${APP_USER} --datadir=/var/lib/mysql

COPY ./conf/my.cnf /etc/my.cnf

COPY ./tools/ .

RUN chown -R ${APP_USER}:${APP_USER} /app && \
    chmod -R 750 /app

USER ${APP_USER}:${APP_USER}

EXPOSE 3306

ENTRYPOINT [ "./init.sh" ]