FROM alpine:3.18

LABEL "mariadb-version"="10.11.4-r0"

WORKDIR /app

ARG APP_USER=mysql MARIADB_VERSION=10.11.4-r0

RUN apk -U upgrade && \
    apk add --no-cache mariadb=${MARIADB_VERSION} mariadb-client=${MARIADB_VERSION} vim openrc

COPY ./conf/my.cnf /etc/mysql/my.cnf
COPY ./conf/my.cnf /etc/mysql/mariadb.conf.d/my.cnf
COPY ./conf/my.cnf /etc/my.cnf.d/mariadb-server.cnf

RUN mkdir -p /var/run/mysqld && \
    chown -R ${APP_USER}:${APP_USER} /var/run/mysqld && \
    chmod -R 755 /var/run/mysqld && \
    mkdir -p /var/lib/mysql && \
    chown -R ${APP_USER}:${APP_USER} /var/lib/mysql && \
    chmod -R 755 /var/lib/mysql && \
    mkdir -p /var/log/mysql && \
    chown -R ${APP_USER}:${APP_USER} /var/log/mysql && \
    chmod -R 755 /var/log/mysql


RUN mysql_install_db --user=${APP_USER} --datadir=/var/lib/mysql

COPY ./tools/ .

RUN chown ${APP_USER}:${APP_USER} ./init.sh && \
    chmod +x ./init.sh

EXPOSE 3306

USER ${APP_USER}:${APP_USER}

ENTRYPOINT [ "./init.sh" ]