FROM alpine:3.18.0

WORKDIR /app

ARG SSHD_VERSION=9.3_p1-r3

RUN apk -U update && apk add --no-cache openssh=${SSHD_VERSION}

COPY conf/sshd_config /etc/ssh/sshd_config

RUN ssh-keygen -A

COPY tools/init.sh .

RUN chmod +x ./init.sh

EXPOSE 3005

CMD ["./init.sh"]