FROM alpine:3.18.0

WORKDIR /usr/share/webapps/adminer

ARG APP_USER=adminer WGET_VERSION=1.21.4-r0

RUN addgroup -S ${APP_USER} && adduser -S ${APP_USER} -G ${APP_USER}

RUN apk -U upgrade && apk add --no-cache wget=${WGET_VERSION} \
    php81 \
    php81-fpm \ 
    php81-ctype \
    php81-phar \
    php81-fpm \ 
    php81-opcache \
    php81-gd \
    php81-mysqli \
    php81-zlib \
    php81-curl \
    php81-mbstring \
    php81-json \
    php81-session \
    php81-tokenizer

RUN mkdir -p /var/log/php-fpm

RUN chown -R ${APP_USER}:${APP_USER} /var/log/php81 && \
    chmod -R 755 /var/log/php81 && \
    chown -R ${APP_USER}:${APP_USER}  /var/log/php-fpm && \
    chmod -R 755 /var/log/php-fpm && \
    chown -R ${APP_USER}:${APP_USER}  /etc/php81 && \
    chmod -R 755 /etc/php81

RUN wget -O index.php https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1-mysql.php

RUN chmod -R 744 /usr/share/webapps/adminer && \
    chown -R ${APP_USER}:${APP_USER} /usr/share/webapps/adminer

USER ${APP_USER}:${APP_USER}

CMD ["php-fpm81", "-F"]