FROM alpine:3.15

ARG APP_USER=www-data

RUN delgroup ${APP_USER} && addgroup -S ${APP_USER} && adduser -S ${APP_USER} -G ${APP_USER}

WORKDIR /app

RUN apk update && apk add --no-cache curl \
    wget \
    php7 \ 
    php7-phar \
    php7-fpm \ 
    php7-opcache \
    php7-gd \
    php7-mysqli \
    php7-zlib \
    php7-curl \
    php7-mbstring \
    php7-json \
    php7-session \
    mariadb-client

COPY ./tools/ /app/

RUN chown -R ${APP_USER}:${APP_USER} /app && \
    chmod -R 750 /app && \
    chown -R ${APP_USER}:${APP_USER} /var/log/php7 && \
    chmod -R 755 /var/log/php7

RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
	chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp

WORKDIR /usr/share/webapps/wordpress

RUN wp core download --version=6.2.2 && \
    chown -R ${APP_USER}:${APP_USER} /usr/share/webapps && \
    chmod -R 755 /usr/share/webapps

USER ${APP_USER}:${APP_USER}

ENTRYPOINT ["/app/init.sh"]