FROM alpine:3.15

LABEL "wordpress-version"="6.2.2"
LABEL "mariadb-version"="10.6.14-r0"
LABEL "php-version"="7.4.33-r1"
LABEL "wget-version"="1.21.2-r2"

ARG APP_USER=www-data WORDPRESS_VERSION=6.2.2  MARIADB_VERSION=10.6.14-r0 PHP_VERSION=7.4.33-r1 WGET_VERSION=1.21.2-r2

RUN delgroup ${APP_USER} && addgroup -S ${APP_USER} && adduser -S ${APP_USER} -G ${APP_USER}

WORKDIR /app

RUN apk -U update && apk add --no-cache curl \
    wget=${WGET_VERSION} \
    php7 \ 
    php7-phar \
    php7-fpm \ 
    php7-opcache \
    php7-gd \
    php7-mysqli \
    php7-zlib \
    php7-curl \
    php7-mbstring \
    php7-json \
    php7-session \
    php7-redis \
    mariadb-client=${MARIADB_VERSION}

COPY ./tools/ /app/

RUN mkdir -p /var/log/php-fpm

COPY ./conf/www.conf /etc/php7/php-fpm.d/www.conf

RUN chown -R ${APP_USER}:${APP_USER} /app && \
    chmod -R 755 /app && \
    chown -R ${APP_USER}:${APP_USER} /var/log/php7 && \
    chmod -R 755 /var/log/php7 && \
    chown -R ${APP_USER}:${APP_USER}  /var/log/php-fpm && \
    chmod -R 755 /var/log/php-fpm && \
    chown -R ${APP_USER}:${APP_USER}  /etc/php7 && \
    chmod -R 755 /etc/php7

RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
	chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp

WORKDIR /usr/share/webapps/wordpress

RUN wp core download --version=${WORDPRESS_VERSION} && \
    chown -R ${APP_USER}:${APP_USER} /usr/share/webapps/wordpress && \
    chmod -R 755 /usr/share/webapps

USER ${APP_USER}:${APP_USER}

ENTRYPOINT ["/app/init.sh"]