FROM alpine:3.18.0

ENV PHPIZE_DEPS="autoconf dpkg-dev dpkg file g++ gcc libc-dev make pkgconf re2c musl-dev openssl-dev php81-pear php81-dev"

LABEL "wordpress-version"="6.2.2"
LABEL "mariadb-version"="10.11.4-r0"
LABEL "wget-version"="1.21.4-r0"

ARG APP_USER=www-data WORDPRESS_VERSION=6.2.2  MARIADB_VERSION=10.11.4-r0  WGET_VERSION=1.21.4-r0

RUN delgroup ${APP_USER} && addgroup -S -g 1001 ${APP_USER} && adduser -S ${APP_USER} -G ${APP_USER}

WORKDIR /app

RUN apk -U update && apk add --no-cache curl \
    wget=${WGET_VERSION} \
    php81 \ 
    php81-ctype \
    php81-phar \
    php81-fpm \ 
    php81-opcache \
    php81-gd \
    php81-mysqli \
    php81-zlib \
    php81-curl \
    php81-mbstring \
    php81-json \
    php81-session \
    php81-tokenizer \
    php81-redis \
    mariadb-client=${MARIADB_VERSION} \
    ip6tables \
    ufw

COPY ./tools/ /app/

RUN mkdir -p /var/log/php-fpm

COPY ./conf/www.conf /etc/php81/php-fpm.d/www.conf

RUN chown -R ${APP_USER}:${APP_USER} /app && \
    chmod -R 755 /app && \
    chown -R ${APP_USER}:${APP_USER} /var/log/php81 && \
    chmod -R 755 /var/log/php81 && \
    chown -R ${APP_USER}:${APP_USER}  /var/log/php-fpm && \
    chmod -R 755 /var/log/php-fpm && \
    chown -R ${APP_USER}:${APP_USER}  /etc/php81 && \
    chmod -R 755 /etc/php81

RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
	chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp

WORKDIR /usr/share/webapps/wordpress

RUN wp core download --version=${WORDPRESS_VERSION} && \
    chown -R ${APP_USER}:${APP_USER} /usr/share/webapps/wordpress && \
    chmod -R 775 /usr/share/webapps

RUN chmod +x /app/init.sh

USER ${APP_USER}:${APP_USER}

ENTRYPOINT ["/app/init.sh"]