FROM alpine:3.18.0

WORKDIR /app/nest

ARG NODEJS_VERSION=18.16.1-r0  NPM_VERSION=9.6.6-r0

RUN apk -U update && apk add --no-cache nodejs=${NODEJS_VERSION} \
    npm=${NPM_VERSION}

EXPOSE 3000

CMD ["npm", "run", "start:dev"]