CREATE DATABASE IF NOT EXISTS `${MARIADB_DB_NAME}`;

CREATE USER IF NOT EXISTS '${ADMIN_USERNAME}'@'localhost' IDENTIFIED BY '${ADMIN_PASSWORD}';

GRANT ALL PRIVILEGES ON `${MARIADB_DB_NAME}`.* TO '${ADMIN_USERNAME}'@'%' IDENTIFIED BY '${ADMIN_PASSWORD}';

ALTER USER 'root'@'localhost' IDENTIFIED BY '${ROOT_PASSWORD}';

DROP DATABASE IF EXISTS test;

CREATE DATABASE wordpress;

FLUSH PRIVILEGES;
