CREATE DATABASE IF NOT EXISTS `${MARIADB_DB_NAME}`;

CREATE USER IF NOT EXISTS '${MARIADB_ADMIN_USERNAME}'@'localhost' IDENTIFIED BY '${MARIADB_ADMIN_PASSWORD}';

GRANT ALL PRIVILEGES ON `${MARIADB_DB_NAME}`.* TO '${MARIADB_ADMIN_USERNAME}'@'%' IDENTIFIED BY '${MARIADB_ADMIN_PASSWORD}';

ALTER USER 'root'@'localhost' IDENTIFIED BY '${MARIADB_ROOT_PASSWORD}';

DROP DATABASE IF EXISTS test;

CREATE DATABASE wordpress;

FLUSH PRIVILEGES;
