FROM alpine:3.18

WORKDIR /app

ARG APP_USER=www-data

RUN delgroup ${APP_USER} && addgroup -S ${APP_USER} && adduser -S ${APP_USER} -G ${APP_USER}

RUN apk -U upgrade && \
    apk add --no-cache nginx openssl

COPY conf/nginx.conf /etc/nginx/nginx.conf

COPY conf/dtoure.42.conf .

RUN mkdir -p /etc/nginx/ssl/private && mkdir -p /etc/nginx/ssl/certs

RUN openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 \
    -config ./dtoure.42.conf \
    -keyout /etc/nginx/ssl/private/dtoure.42.key -out /etc/nginx/ssl/certs/dtoure.42.crt

RUN chmod -R 755 /var/lib/nginx /var/log/nginx /etc/nginx /var/run/nginx

RUN chown -R ${APP_USER}:${APP_USER} /var/lib/nginx /var/log/nginx /etc/nginx /var/run/nginx

USER ${APP_USER}:${APP_USER}

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
