FROM alpine:3.18

LABEL "nginx-version"="1.24.0-r9"
LABEL "openssl-version"="3.1.1-r1"

WORKDIR /app

ARG APP_USER=www-data NGINX_VERSION=1.24.0-r6 OPENSSL_VERSION=3.1.1-r1 

RUN delgroup ${APP_USER} && addgroup -S -g 1001 ${APP_USER} && adduser -S ${APP_USER} -G ${APP_USER}

RUN apk -U upgrade && \
    apk add --no-cache nginx=${NGINX_VERSION} openssl=${OPENSSL_VERSION}

COPY conf/nginx.conf /etc/nginx/nginx.conf

COPY conf/dtoure.42.conf .

RUN mkdir -p /etc/nginx/ssl/private && mkdir -p /etc/nginx/ssl/certs

RUN openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 \
    -config ./dtoure.42.conf \
    -keyout /etc/nginx/ssl/private/dtoure.42.key -out /etc/nginx/ssl/certs/dtoure.42.crt

RUN mkdir -p /var/log/nginx/wordpress && \
    touch /var/log/nginx/wordpress/access.log && \
    touch /var/log/nginx/wordpress/error.log && \
    mkdir -p /var/log/nginx/adminer && \
    touch /var/log/nginx/adminer/access.log && \
    touch /var/log/nginx/adminer/error.log

RUN chmod -R 755 /var/lib/nginx && \
    chown -R ${APP_USER}:${APP_USER} /var/lib/nginx && \ 
    chmod -R 755 /var/log/nginx && \
    chown -R ${APP_USER}:${APP_USER} /var/log/nginx && \ 
    chmod -R 755 /var/run/nginx && \
    chown -R ${APP_USER}:${APP_USER} /var/run/nginx && \
    chmod -R 755 /etc/nginx && \
    chown -R ${APP_USER}:${APP_USER} /etc/nginx

USER ${APP_USER}:${APP_USER}

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
