
FROM alpine:3.18.0

LABEL "redis-version"="7.0.11-r0"

ARG APP_USER=redis-user REDIS_VERSION=7.0.11-r0

RUN addgroup -S ${APP_USER} && adduser -S ${APP_USER} -G ${APP_USER}

WORKDIR /app

RUN mkdir -p /var/run/redis && \
    chown -R ${APP_USER}:${APP_USER} /var/run/redis && \
    chmod -R 777 /var/run/redis && \
    mkdir -p /var/log/redis && \
    chown -R ${APP_USER}:${APP_USER} /var/log/redis && \
    chmod -R 755 /var/log/redis

RUN apk -U update && apk add --no-cache redis=${REDIS_VERSION} \
    openrc \
    procps 

COPY ./conf/redis.conf /etc/redis.conf

RUN mkdir -p /var/lib/redis && \
    chown -R ${APP_USER}:${APP_USER} /var/lib/redis && \
    chmod -R 755 /var/lib/redis && \
    chown ${APP_USER}:${APP_USER} /etc/redis.conf && \
    chmod 755 /etc/redis.conf

EXPOSE 6379

USER ${APP_USER}:${APP_USER}

CMD ["redis-server", "/etc/redis.conf"]