version: '3'

services:
    vsftpd:
      build:
        context: '.'
        dockerfile: Dockerfile-vsftpd
      image: vsftpd-image:v1
      ports:
        - 20:20
        - 21:21
        - 30000-30010:30000-30010
      env_file : ../../../.env

networks:
  wp-nginx-mariadb: